### ISSUE TITLE
Decide how to Authenticate Users of the Turing BinderHub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#290]
### Summary

Decide on the most appropriate method of authenticating users of the Turing BinderHub.

Currently have GitHub authentication working with the following config:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: sgibson91/BHtest2-dev-
    hub_url: http://<redacted>
    auth_enabled: true

jupyterhub:
  cull:
    # don't cull authenticated users
    users: False

  hub:
    services:
      binder:
        oauth_redirect_uri: "http://<redacted>/oauth_callback"
        oauth_client_id: "binder-oauth-client-test"
    extraConfig:
      hub_extra: |
        c.JupyterHub.redirect_to_server = False

      binder: |
        from kubespawner import KubeSpawner

        class BinderSpawner(KubeSpawner):
          def start(self):
            if 'image' in self.user_options:
              # binder service sets the image spec via user options
              self.image = self.user_options['image']
            return super().start()
        c.JupyterHub.spawner_class = BinderSpawner

  singleuser:
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser

  auth:
    type: github
    github:
      clientId: "<redacted>"
      clientSecret: "<redacted>"
      callbackUrl: "http://<redacted>/hub/oauth_callback"
```
Adapted from these docs:
* https://binderhub.readthedocs.io/en/latest/authentication.html
* https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#github

And with the addition of the following config, GitHub users would need to be a member of the Alan Turing Institute organisation on GitHub to gain access (not tested yet). Adapted from here: https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#giving-access-to-organizations-on-github
```
auth:
    type: github
    github:
      orgWhitelist:
        - "alan-turing-institute"
    scopes:
      - "read:user"
```

This would allow any member of the Turing GitHub organisation to access the BinderHub and launch **any public** repo.

However, there is also the option to authenticate using Active Directory, see the following link:
* https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#example-active-directory-configuration

### What needs to be done?

- [ ] Pros/Cons of GitHub and Active Directory Authentication
- [ ] Have authentication work for HTTPS wed addresses
- [ ] Get OAuth with GitHub organisations working

### Who can help?

* Anyone with knowledge of Authentication protocols, either GitHub or Azure specific

---

### Updates

**07/03/2019** - Successfully got organisational authentication for BinderHub working using `auth: scopes: read:org`. Some reading to convince ourselves this is only accessing organisation/team memberships is required. [Docs here.](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes)
